version: 2
jobs:
  node-v10-latest:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Node 12 and Run Tests
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 12
            nvm alias default 12
            node --version && npm --version
            npm install
            npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success

workflows:
  version: 2
  validate:
    jobs:
      - node-v10-latest:
          filters:
            tags:
              only: /.*/
