version: 2
jobs:
  node-v10-latest:
    machine:
      image: circleci/node:12.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Node Info
          command: node --version && npm --version
      - run:
          name: NPM Rebuild
          command: npm install
      - run:
          name: Run unit tests.
          command: npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success

workflows:
  version: 2
  validate:
    jobs:
      - node-v10-latest:
          filters:
            tags:
              only: /.*/
